### ISSUE TITLE
Wrong version of ffmpeg?

### ISSUE THREAD

**Issue by jmgiaever** [IsaacJT/jellyfin-snap#6]
Output of `/snap/itrue-jellyfin/current/usr/lib/jellyfin-ffmpeg/ffmpeg` doesn't comply with the [recommended](https://jellyfin.org/docs/general/administration/hardware-acceleration/#full--partial-acceleration) version of `ffmpeg`.

You can verify this with 
```
sudo snap run --shell itrue-jellyfin.server
cd $SNAP
./usr/lib/jellyfin-ffmpeg/ffmpeg
```

**Comment by IsaacJT** [comment]
Thanks @jmgiaever this is a good point. Currently the snap just uses whatever version of ffmpeg that Ubuntu provides, but adding ffmpeg-jellyfin sounds sensible.

I'll work on adding it soon

**Comment by jmgiaever** [comment]
Awesome. Thanks! 🙏

**Comment by IsaacJT** [comment]
Hi, this is now available in the edge channel for amd64 (rev 76). Please give it a try :)

```
# $SNAP/usr/lib/jellyfin-ffmpeg/ffmpeg
ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
```

**Comment by jmgiaever** [comment]
Hi,

I only have arm64 to test with. Can you build it for arm64 too,  please? 😀

**Comment by IsaacJT** [comment]
Should be available now for arm64 and armhf (rev 79 and 78)

**Comment by jmgiaever** [comment]
Great, thanks. 

Should there be a symbolic link to this version in $SNAP/usr/bin?

**Comment by IsaacJT** [comment]
It shouldn't be needed as the location is passed as an argument to the jellyfin server daemon

**Comment by jmgiaever** [comment]
Hi,

Seems there's an issue with the plugin "Intro Skipper", with regards to `ffmpeg`. 

```
[2023-05-30 02:13:23.589 +02:00] [INF] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Detect Introductions"
[2023-05-30 02:13:23.592 +02:00] [ERR] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: ffmpeg with chromaprint is not installed on this system - episodes will not be analyzed. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade it to the latest version of 10.8.0.
   at ConfusedPolarBear.Plugin.IntroSkipper.QueueManager.EnqueueAllEpisodes()
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2023-05-30 02:13:23.594 +02:00] [INF] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Introductions" Failed after 0 minute(s) and 0 seconds
[2023-05-30 02:13:23.596 +02:00] [INF] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

Could it be that it's trying to use `ffmpeg` from `PATH` (`/usr/bin/ffmpeg` or similar)?

**Comment by IsaacJT** [comment]
Hi, this might be something to do with the plugin not supporting `jellyfin-ffmpeg6`. libchromaprint support is enabled and the plugin is present 

Jellyfin is also correctly finding the ffmpeg binary:

```
2023-05-30T11:52:27+02:00 itrue-jellyfin.server[210691]: [11:52:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 6.0
2023-05-30T11:52:27+02:00 itrue-jellyfin.server[210691]: [11:52:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc
_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
2023-05-30T11:52:27+02:00 itrue-jellyfin.server[210691]: [11:52:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf",
"hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
2023-05-30T11:52:27+02:00 itrue-jellyfin.server[210691]: [11:52:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_q
sv", "overlay_vaapi", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
2023-05-30T11:52:27+02:00 itrue-jellyfin.server[210691]: [11:52:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
```

Going into the "Support Bundle" option of the plugin also shows that it's been detected correctly:

```
* Jellyfin version: 10.8.10
* Plugin version: 0.1.7
* Queue contents: 28 episodes, 2 seasons
* FFmpeg: `okay`

FFmpeg version:
ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
